### ISSUE TITLE
[Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail/[tmp_file_name]

### ISSUE THREAD

**Issue by ondraknezour** [modoboa/modoboa-webmail#212] opened 2021-02-02 12:41 UTC
When trying to forward message from the webmail, I got error message [Errno 2] No such file or directory: '/srv/modoboa/instance/media/webmail/... and it is true, only modoboa_webmail directory is there. Creating symbolic link modoboa_webmail -> webmail solves the problem for now, but this should be fixed somewhere else.

**Comment by harryfoster** [comment] 2021-02-10 15:14
Probably a duplicate of this: #196

**Closed** 2021-02-11 20:03 UTC
